module.exports = {
    PLANILLA_DE_CARGA : "PLANILLA_DE_CARGA",
    USER_LISTADO : "USER_LISTADO",
    PAGOS_ADMIN : "PAGOS_ADMIN",
    PAGOS_USER : "PAGOS_USER",
    PAGOS_GERENCIA: "PAGOS_GERENCIA",
    RENDICION_ADMIN : "RENDICION_ADMIN",
    VENTAS_USER : "VENTAS_USER",
    VENTAS_ADMIN : "VENTAS_ADMIN",
    VENTAS_GERENCIA : "VENTAS_GERENCIA"
}