module.exports = {
    PLANILLA_DE_CARGA : "PLANILLA_DE_CARGA",
    USER_LISTADO : "USER_LISTADO",
    PAGOS_ADMIN : "PAGOS_ADMIN",
    PAGOS_USER : "PAGOS_USER",
    RENDICION_ADMIN : "RENDICION_ADMIN",
    PAGOS_GERENCIA: "PAGOS_GERENCIA",
    VENTAS_USER : "VENTAS_USER"
}